ALTER TABLE orders
ADD COLUMN IF NOT EXISTS sku TEXT;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS variant TEXT;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS address JSONB;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS warehouse_order_id TEXT;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS warehouse_status TEXT;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS warehouse_payload JSONB;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS reviewed_by TEXT REFERENCES users(id);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS rejection_note TEXT;

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

CREATE INDEX IF NOT EXISTS idx_orders_sku ON orders(sku);
